export const API_ENDPOINTS = {
  HEALTH: '/health',
  AUTH: {
    LOGIN: '/auth/login',
    REFRESH: '/auth/refresh',
    VERIFY: '/auth/verify',
    LOGOUT: '/auth/logout',
    LOGOUT_ALL: '/auth/logout-all',
  },
  USERS: {
    ME: '/users/me',
    GOTIFY_CONFIG: '/users/me/gotify',
    RECONCILE_GOTIFY: '/users/reconcile-gotify',
    LIST: '/users',
    CREATE: '/users',
    DETAIL: (id: string) => `/users/${id}`,
    UPDATE: (id: string) => `/users/${id}`,
    DELETE: (id: string) => `/users/${id}`,
    PROVISION_GOTIFY: (id: string) => `/users/${id}/provision-gotify`,
  },
  ROLES: {
    LIST: '/roles',
    CREATE: '/roles',
    DETAIL: (id: string) => `/roles/${id}`,
    UPDATE: (id: string) => `/roles/${id}`,
    DELETE: (id: string) => `/roles/${id}`,
    PERMISSIONS: (id: string) => `/roles/${id}/permissions`,
  },
  PERMISSIONS: {
    LIST: '/permissions',
    CREATE: '/permissions',
    DETAIL: (id: string) => `/permissions/${id}`,
    DELETE: (id: string) => `/permissions/${id}`,
  },
  ORGANIZATIONS: {
    LIST: '/organizations',
    CREATE: '/organizations',
    DETAIL: (id: string) => `/organizations/${id}`,
    UPDATE: (id: string) => `/organizations/${id}`,
    DELETE: (id: string) => `/organizations/${id}`,
  },
  GROUPS: {
    LIST: '/groups',
    CREATE: '/groups',
    DETAIL: (id: string) => `/groups/${id}`,
    UPDATE: (id: string) => `/groups/${id}`,
    DELETE: (id: string) => `/groups/${id}`,
    USERS: (id: string) => `/groups/${id}/users`,
    USER: (groupId: string, userId: string) => `/groups/${groupId}/users/${userId}`,
  },
  BRANCHES: {
    LIST: '/groups',
    CREATE: '/groups',
    DETAIL: (id: string) => `/groups/${id}`,
    UPDATE: (id: string) => `/groups/${id}`,
    DELETE: (id: string) => `/groups/${id}`,
    USERS: (id: string) => `/groups/${id}/users`,
    USER: (branchId: string, userId: string) => `/groups/${branchId}/users/${userId}`,
  },
  SITES: {
    LIST: '/sites',
    CREATE: '/sites',
    DETAIL: (id: string) => `/sites/${id}`,
    UPDATE: (id: string) => `/sites/${id}`,
    DELETE: (id: string) => `/sites/${id}`,
  },
  ACTION_STATUSES: {
    LIST: '/action-statuses',
    CREATE: '/action-statuses',
    DETAIL: (id: string) => `/action-statuses/${id}`,
    UPDATE: (id: string) => `/action-statuses/${id}`,
    DELETE: (id: string) => `/action-statuses/${id}`,
  },
  ACTIONS: {
    LIST: '/actions',
    DETAIL: (id: string) => `/actions/${id}`,
    CREATE: '/actions',
    UPDATE: (id: string) => `/actions/${id}`,
    DELETE: (id: string) => `/actions/${id}`,
    ASSIGNEES: (id: string) => `/actions/${id}/assignees`,
    ASSIGNEE: (actionId: string, userId: string) => `/actions/${actionId}/assignees/${userId}`,
  },
  INSPECTIONS: {
    LIST: '/inspections',
    SUBMIT_ONE_SHOT: '/inspections/submit',
    DASHBOARD_STATS: '/inspections/dashboard',
    CPS_WEEKLY_SCORE: '/inspections/cps/weekly-score',
    CREATE: '/inspections',
    DETAIL: (id: string) => `/inspections/${id}`,
    SUBMIT: (id: string) => `/inspections/${id}/submit`,
    EXPORT_REPORT: (id: string) => `/inspections/${id}/report.xlsx`,
    EXPORT_ISSUES: (id: string) => `/inspections/${id}/issues.xlsx`,
    DELETE: (id: string) => `/inspections/${id}`,
    FIELD_VALUES: (inspectionId: string) => `/inspections/${inspectionId}/field-values`,
    FIELD_VALUE_FLAG: (inspectionId: string, valueId: string) =>
      `/inspections/${inspectionId}/field-values/${valueId}/flag`,
    SCORES: (inspectionId: string) => `/inspections/${inspectionId}/scores`,
    ATTACHMENTS: (inspectionId: string) => `/inspections/${inspectionId}/attachments`,
    ATTACHMENT_UPLOAD: (inspectionId: string) => `/inspections/${inspectionId}/attachments/upload`,
    ATTACHMENT: (inspectionId: string, attachmentId: string) =>
      `/inspections/${inspectionId}/attachments/${attachmentId}`,
    TABLES: (inspectionId: string) => `/inspections/${inspectionId}/tables`,
    TABLE_ROWS: (inspectionId: string, tableId: string) =>
      `/inspections/${inspectionId}/tables/${tableId}/rows`,
    TABLE_ROW_CELLS: (inspectionId: string, tableId: string, rowId: string) =>
      `/inspections/${inspectionId}/tables/${tableId}/rows/${rowId}/cells`,
  },
  TEMPLATES: {
    LIST: '/templates',
    DETAIL: (id: string) => `/templates/${id}`,
    CREATE: '/templates',
    BUILD: '/templates/build',
    PREVIEW: (id: string) => `/templates/${id}/preview`,
    UPDATE: (id: string) => `/templates/${id}`,
    UPDATE_BUILD: (id: string) => `/templates/${id}/build`,
    PUBLISH: (id: string) => `/templates/${id}/publish`,
    DELETE: (id: string) => `/templates/${id}`,
    VERSIONS: (templateId: string) => `/templates/${templateId}/versions`,
    VERSION: (templateId: string, versionId: string) => `/templates/${templateId}/versions/${versionId}`,
    VERSION_DETAIL: (templateId: string, versionId: string) =>
      `/templates/${templateId}/versions/${versionId}/detail`,
    PUBLISH_VERSION: (templateId: string, versionId: string) =>
      `/templates/${templateId}/versions/${versionId}/publish`,
    PAGES: (templateId: string, versionId: string) =>
      `/templates/${templateId}/versions/${versionId}/pages`,
    PAGE_FIELDS: (templateId: string, versionId: string, pageId: string) =>
      `/templates/${templateId}/versions/${versionId}/pages/${pageId}/fields`,
  },
  TEMPLATE_VERSIONS: {
    UPDATE: (id: string) => `/template-versions/${id}`,
  },
  SECTIONS: {
    CREATE: (versionId: string) => `/sections?versionId=${versionId}`,
    UPDATE: (id: string) => `/sections/${id}`,
    DELETE: (id: string) => `/sections/${id}`,
    DUPLICATE: (id: string) => `/sections/${id}/duplicate`,
    REORDER: (versionId: string) => `/sections/reorder?versionId=${versionId}`,
  },
  FIELDS: {
    CREATE: (sectionId: string) => `/fields?sectionId=${sectionId}`,
    UPDATE: (id: string) => `/fields/${id}`,
    DELETE: (id: string) => `/fields/${id}`,
    REORDER: (sectionId: string) => `/fields/reorder?sectionId=${sectionId}`,
  },
  MASTER_FIELDS: {
    LIST: '/master-fields',
    CREATE: '/master-fields',
    DETAIL: (id: string) => `/master-fields/${id}`,
    UPDATE: (id: string) => `/master-fields/${id}`,
    DELETE: (id: string) => `/master-fields/${id}`,
    OPTIONS: (id: string) => `/master-fields/${id}/options`,
    OPTION: (id: string, optionId: string) => `/master-fields/${id}/options/${optionId}`,
    CREATE_FROM_MASTER: (sectionId: string) => `/fields/from-master?sectionId=${sectionId}`,
  },
  CPS: {
    LIST: '/cps',
  },
  TRAINING: {
    LIST: '/training',
  },
  PROFILE: {
    ME: '/profile/me',
    UPDATE: '/profile/me',
    UPLOAD_AVATAR: '/profile/me/avatar',
  },
  NOTIFICATIONS: {
    LIST: '/notifications',
    UNREAD_COUNT: '/notifications/unread-count',
    MARK_READ: (id: string) => `/notifications/${id}/read`,
    MARK_ALL_READ: '/notifications/read-all',
  },
  RULES: {
    METADATA: '/rules/metadata',
  },
  DOCUMENTS: {
    FOLDERS: '/documents/folders',
    FOLDER: (id: string) => `/documents/folders/${id}`,
    FOLDER_SHARE: (id: string) => `/documents/folders/${id}/share`,
    FOLDER_UNSHARE: (folderId: string, shareId: string) =>
      `/documents/folders/${folderId}/share/${shareId}`,
    UPLOAD: '/documents/upload',
    DETAIL: (id: string) => `/documents/${id}`,
    DOWNLOAD: (id: string) => `/documents/${id}/download`,
    SHARE: (id: string) => `/documents/${id}/share`,
    UNSHARE: (documentId: string, shareId: string) => `/documents/${documentId}/share/${shareId}`,
    TRASH: '/documents/trash',
    RESTORE: (id: string) => `/documents/trash/${id}/restore`,
    PERMANENT_DELETE: (id: string) => `/documents/trash/${id}`,
  },
};
